name: Pull request check

on:
  pull_request:
    branches: [ main ]

jobs:

  quality-assurance:
    name: Quality Assurance
    uses: ./.github/workflows/quality-assurance.yml

  validate-version:
    name: Validate version
    uses: ./.github/workflows/validate-current-version.yml
    needs: quality-assurance