name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  quality-assurance:
    name: Quality Assurance
    uses: ./.github/workflows/quality_assurance.yml

  release-notes-generation:
    name: Release generation
    uses: ./.github/workflows/release_notes_generation.yml
    needs: quality-assurance

#  TODO create and send pip package
