name: Package publishing to pypi

on: [workflow_call]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install build dependencies
      run: python -m pip install -U setuptools wheel build
    - name: Build
      run: |
        python setup.py bdist_wheel sdist
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
#        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
